---
title: "Downloaders"
embed-resources: true
filters:
    - sorting-hat
    - ripper
extensions:
    sorting-hat:
      keep:
        - r
      verbose: true
    ripper:
      include-yaml: false
      output-dir: "../R"
      output-name: "downloaders"
      script-links-position: "none"
execute: 
  eval: false
params:
  testing: false
---

In this notebook, we'll define some functions that
will help us download the data that was set up in the Qualtrics survey.

As a reminder, whenever we have data that the lab will want access
to, we ask lab members to fill out a data intake form on Qualtrics.
This form includes some metadata, but importantly, it differentiates
between data that is expected to be larger than 50mb, and data that is expected
to be smaller than 50mb. This is because Qualtrics has a file size 
limit of 50mb, so we have to use different download methods for data 
above and below that threshold. Below that threshold, we can directly
download the data. Above that threshold, and we assume that the uploader
followed the instructions in the survey and was able to upload their
data to our public globus endpoint, and then provided us with the file
name of their uploaded data, we can use that information to download the data from globus.

First, let's deal with the case that the data is expected to be smaller than 50mb.
```{r}

download_from_qualtrics <- function(download_url, output_dir) {
  # This function will download a file from the given URL and save it to the specified output directory.
  # It assumes that the download_url is a direct link to the file.
  
  # Create the output directory if it doesn't exist
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
  }
  
  # Extract the file name from the URL
  file_name <- basename(download_url)
  
  # Define the full path to save the downloaded file
  output_path <- file.path(output_dir, file_name)
  
  # Download the file
  download.file(download_url, destfile = output_path, mode = "wb")
  
  return(output_path)
}
```
